name 'bazaar'
maintainer 'JJ Asghar'
maintainer_email 'jj@chef.io'
license 'Apache 2'
description 'Installs/Configures bazaar'
long_description 'Installs/Configures bazaar'
version '1.0.0'

depends 'yum'
depends 'apt'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'fedora'
